all:
	cc -g ../get_next_line.o ../get_next_line_utils.o test.c test.h
f fclean:
	rm -rf *.o *.h.gch *.out
re: f all
bonus:
	cc -g ../get_next_line_bonus.o ../get_next_line_utils_bonus.o test.c test.h

